"""add_use_nickname_for_certificates_to_users

Revision ID: 02e0e2e1a9bb
Revises: 0018_create_certificates
Create Date: 2026-02-20 21:05:21.656536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e0e2e1a9bb'
down_revision: Union[str, None] = '0018_create_certificates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('use_nickname_for_certificates', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'use_nickname_for_certificates')
    # ### end Alembic commands ###
