"""add_image_url_to_support_messages

Revision ID: 82d2320925a0
Revises: aaa1cc549112
Create Date: 2026-02-22 08:02:52.729027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d2320925a0'
down_revision: Union[str, None] = 'aaa1cc549112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_messages', 'image_url')
    # ### end Alembic commands ###
